### ISSUE TITLE
アドオンのWebExtensions対応

### ISSUE THREAD

**Issue by fujimotos** [clear-code/reload-on-idle#1]
## WebExtensionsへの移行について

MozillaのAPIリファレンスを読んでいて気がついたのですが、
このアドオンは次の3つのAPIを使えばWebExtensions化できそうです：

 * [Idle API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/idle)
 * [Tabs API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs)
 * [Alarms API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/alarms)

大きな判定処理のフローとしては、

 1. 端末のアクティブ／休眠状態を`Idle API`を通じて取得する
 2. 判定条件「X秒間活動無し」を満たしていれば、`Tabs API`を通じて各タブにリロードをかける

という流れです。この判定処理を、`Alarms API`を使って背後で定期的に立ち上げれば、
今のXPCOMベースのアドオンとほぼ同等の機能性を実現できるのでは、と考えています。

### 実装サンプル

言葉の説明だけだと分かりにくいので、上の処理の骨組だけを実際に組み立ててみました：

**background.js**
```javascript
function reloadTabs() {
  browser.tabs.query({})
    .then((tabs) => {
      for (let tab of tabs) {
        browser.tabs.reload(tab.id);
      }
    });
};

/**
 * Check if the computer is in idle state
 */
browser.alarms.onAlarm.addListener((alarm) => {
  browser.idle.queryState(120)  // 2 min
    .then((info) => {
      if (info === 'idle') {
        reloadTabs();
      }
    });
});

/**
 * Create a periodic alarm
 */
browser.alarms.create("idle-reload-alarm", {
  periodInMinutes: 0.5 // 30 sec
});
```

アドオンの外装を作って、以上のコードをFirefox実機で動かしてみましたが、
2分間なにも操作をしないと、自動的にタブのリロードが走るところまで確認できました。

### 対応できる範囲／制約

どこまで細かい機能性を再現できるかですが、WebExtensionsのAPI仕様を読む限り、
次の3つのオプションは問題なく対応できそうです：

 * 「対象タブをURLでフィルタする」 -> `tabs.Tab.url`で判定
 * 「読み込み中でもリロードする」 -> `tabs.Tab.status`で判定
 * 「コンソールにログを出力する」 -> 可能

ただ、次の機能は対応するAPIが見つからなかったです：

 * 「編集中のデータがある場合も強制的にリロードする」（document.beforeunload対策？)

また、WebExtensionsのIdle APIだと休眠判定できる最小の時間間隔が「15秒」のようです。
実際に、`browsers.idle.queryState(10)` を実行すると次のエラーがでます：

![2017-09-16-122814_418x43_scrot](https://user-images.githubusercontent.com/8974561/30510336-f412643c-9afc-11e7-80c4-bb271201c2b3.png)

（ただし、数秒間隔で自動リロードするニーズがあるかはよく分かっていません）

----

@piroor 以上の方針についてどう思われますか？
大きな見落としがなさそうなら、この方向性で少し取り組んでみたいと思います。

**Comment by piroor** [comment]
調査・検討を頂きありがとうございます。大枠ではこんな感じでよさそうです。

>  「編集中のデータがある場合も強制的にリロードする」（document.beforeunload対策？)

これは https://bugzilla.mozilla.org/show_bug.cgi?id=1270784 ですね。（現在はタブをアンロードする機能の要望のbugのDUPLICATEにされてしまってますが……）
現在直接サポートを提供している先のお客様ではないものの、元々のニーズとしてはこの要件が必須なので、これが果たされない事には移植完了とは言えないのが辛いところです。

**Comment by fujimotos** [comment]
> 「編集中のデータがある場合も強制的にリロードする」（document.beforeunload対策？)

https://github.com/clear-code/reload-on-idle/pull/4 の対応で解決したと思われるので、クローズします。
